name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.3.5
  - pip=20.3.3
  - pandas-profiling=3.1.0
  - pyarrow=2.0
  - ipywidgets=7.6.3
  - pip:
      - wandb==0.12.17